# Generated by Django 4.0.5 on 2022-06-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gaghapar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Place name')),
                ('date', models.DateField(verbose_name='Date')),
                ('nums', models.IntegerField(verbose_name='Numbers of travel')),
            ],
            options={
                'verbose_name': 'Date1',
                'verbose_name_plural': 'Dates1',
            },
        ),
    ]
